name: Deploy push master
 on:
    release:
      types: [published]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    
      - uses: actions/checkout@v2 #Reference the major version of a release

      - name: Install Dependencies
        run: npm install

      #- name: firebase install
      #  run: npm install firebase

      - name: same
        run: npm install -g firebase-tools

      - name: Build
        run: npm run build          

      - name: Deploy 
        run: firebase deploy --only hosting --project deploy-4ea47 --token ${{ secrets.FIREBASE_TOKEN }}