name: merge on pull request
  'on': 
    pull_request_target:
        branches:
        - master

jobs :
  Test and Merge:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2 

      - name: Install Dependecies
        run: npm install


      - name: Install Firebase-tools
        run: npm install -g firebase-tools

      - name: Build
        run: npm run build

      - name: test 
        run: echo TEST:OK

      - name: automerge
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      


