name: Pull request
'on':
    pull_request:
        branches:
          - master

jobs :
    Testandmerge:
      runs-on: ubuntu-20.04
      steps:

      - uses: actions/checkout@v2 

      - name: Install Dependecies
        run: npm install


      - name: Install Firebase-tools
        run: npm install -g firebase-tools

      - name: Build
        run: npm run build

      - name: test 
        run: echo TEST:OK



