name: Test push develop
'on':
  push:
    branches:
      - develop

jobs:
  TestDeploy:
    runs-on: ubuntu-20.04
    steps:
    
      - uses: actions/checkout@v2

      - name: Install dependances npm
        run: npm install

      - name: Install Firebase-tools
        run: npm install -g firebase-tools

      - name: npm build
        run: npm run build          

      - name: Marche
        run: echo test:valide